language: bash
dist: xenial
services:
  - docker

env:
  global:
    - secure: Nsr25/kVGMPo3BLwcZFunC+XEFfeq39UfQgbcRXPYXZGGvN03j84OpF6WkM2kWDcBvEkn4Rq5gBLxuQqi33RoLdS7mvPWNGQMz/OvxSZjhPEUENDZ6IdrWN5gFwkapTCEuPDrYwcMGXxz0gYf84j/93A5SsEdvQ4XBf3ZDVBOWD8zVcOP+MxrKHbjEED0Sa+kEIFrw8lVjZJEydo4qS6XfiA8EjJseim/nIg6J/eK2qO4lk0sRDYxcCwNODhjVurVIegmdfol/45ox4GjkqdlEPMLLLjZkLRCxGIww2jBqdMO7pU3hXeqqoxnh093m8z5mtq7cGpK73dZqWjKbl38iWJSPKB+TdnaRS985R8ASFIvcMkplF8Bid70mjNPRyU5jqUxUEQ8CefB5ndTPlnSVya9RZUmUq+d8Iiuj+Y3HV0n4Vpoe4AxMYsbfQN1KfOgHJb8qIjidGsSI65AEr+S7hQVe2vQrIf2Ohpt8MIuVs7BgldK9DcYMg0yi1WGs7uLV3vF/GZ/UrJHaHlVFkY0tDZz5DCMURbk5PUQ94V5b2bF+RwVWAKH9/a+Sr+GTew9F5QyZKXlTLDbzPuq6qAXHilMZe1/NrYq7SNnw5thXT1fyjhbOPn6fF561oFBZQtiz/tLa9J4r5VyGogZNqsLo6uDgZJqOcI8duLHWoQ0ks=

before_install:
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" >> env.list
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH" >> env.list
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" >> env.list
  - echo "ENCRYPTED_PRIVKEY_SECRET=$ENCRYPTED_PRIVKEY_SECRET" >> env.list
  - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> env.list
  - wget https://raw.githubusercontent.com/openSUSE/doc-ci/master/travis/travis.sh

script:
  - docker run --rm -it --volume ${PWD}:/usr/src/app --workdir /usr/src/app susedoc/ci:latest /bin/bash -c '/bin/bash travis.sh'

notifications:
  email:
    on_success: change
    on_failure: always
