= SUSE Cloud Application Platform (CAP) Documentation

image:https://travis-ci.org/SUSE/doc-cap.svg?branch=develop["Build Status", link="https://travis-ci.org/SUSE/doc-cap"]

This is the source for the official SUSE Cloud Application Platform (CAP) Documentation

Released versions of the documentation will be published at
https://documentation.suse.com/ once available.

== Contributing

If you would like to contribute, pull requests are welcome. Always create your working branch from the `develop` branch. You are also welcome to open a GitHub Issue and write your contribution in plain text, and we will take care of the rest.

Contributors with direct access to the repository are encouraged to use the
git-flow-avh workflow (package `git-flow-avh`). However, this is not a must.
For help on style and structure, refer to the https://doc.opensuse.org/products/opensuse/Styleguide/opensuse_documentation_styleguide_sd/[Documentation Styleguide] 


.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is
reserved for releases only. Always commit to `develop`.

== Editing DocBook

If you are interested in learning the official Doc Team way of writing
the official SUSE product documentation, follow these suggestions. 
Our source files are written using DocBook XML and built with DAPS
using custom stylesheets.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). It's available as a
  SUSE rpm package from the the SUSE repository http://download.opensuse.org/repositories/Documentation:/Tools/[Documentation:Tools] or
  directly from https://github.com/openSUSE/suse-xsl/[Github].
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
** Learn more at https://opensuse.github.io/daps
